## Homework

Zadanie wprowadzające z wykladu (dowolny algorytm z tablicą i pętlą)

In [1]:
function insertionSort(a::Array)
    for i in 2:length(a)
        tmp = a[i]
        position = i

        while position > 1 && a[position-1] > tmp
            a[position] = a[position-1]
            position -= 1
        end

        a[position] = tmp
  end
  return a
end

insertionSort (generic function with 1 method)

In [2]:
insertionSort([1,-13,23,22,11,22,3333,98])

8-element Array{Int64,1}:
  -13
    1
   11
   22
   22
   23
   98
 3333

Napisać funkcję, która bierze typ i wypisuje jego graf dziedziczenia np. w formie "Any-->Number-->Real->AbstractFloat-->Float16".

Wskazówka: wewnetrznie typy są reprezentowane jako DataType np.: 
julia> typeof(Real) 
DataType

In [3]:
function printTypeTree(t)
    print(t)
    while(t!=Any)
        t = supertype(t)
        print("<---", t)
    end
end

printTypeTree (generic function with 1 method)

In [4]:
printTypeTree(Float16)

Float16<---AbstractFloat<---Real<---Number<---Any

In [22]:
printTypeTree(Bool)

Bool<---Integer<---Real<---Number<---Any

Napisać prostą symulację świata zwiarząt.
- Zwierzę może być typu Drapieżnik lub Ofiara. Oba te typy powinny dziedziczyć po abstrakcyjnym typie Zwierzę.
- Zwierzęta żyją na kwadratowej planszy NxN, N - dowolnie wybrana (ustalona) liczba. Kazde zwierzę zajmuje jedną kratkę.
- Przetestować wsparcie Julii dla Unicode poprzez użycie polskich znaków.
- Napisać parametryczną funkcję dodawania zwierzęcia do swiata wg podanych współrzędnych działającą dla dowolnego typu pochodnego od Zwierzę. Jeśli miejsce jest zajęte rzucany jest wyjątek.
- Przetestować dodając kilka zwierząt do świata.
- Napisać parametryczną funkcję odległość, ktora oblicza odległość miedzy zwierzętami metryką taksowkową . Funkcja powinna akceptować dowolne typy dziedziczące po typie Zwierzę. Przetesować działanie.
- Napisac funkcję interakcja. Zademonstrować i przetestować mechanizm multiple dispatch pisząc następujące metody tej funkcji:
    - jesli pierwszym argumentem jest zmienna typu Drapieżnik, a drugim zmienna typu Ofiara, Ofiara znika ze swiata.
    - jesli pierwszym argumentem jest zmienna typu Ofiara, a druga typu Drapieżnik, Ofiara ucieka w dowolne inne wolne miejsce
    - jesli obydwoma argumentami sa Drapieżnicy metoda zwraca string "Wrrrr"
    - jsli obydwoma argumentami sa Ofiary metoda zwraca string "Beeee"

In [5]:
abstract Animal
        
type Predator <: Animal
    name::AbstractString
    x::Integer
    y::Integer
 
    Predator(name::String) = new(name, 0, 0)
end

type Victim <: Animal
    name::AbstractString
    x::Integer
    y::Integer
    
    Victim(name::String) = new(name, 0, 0)
end 

In [6]:
function createWorld(n::Integer)
    return fill("#",(n,n)) 
end

createWorld (generic function with 1 method)

In [7]:
#creating world for animals
world = createWorld(10)

10×10 Array{String,2}:
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"
 "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"  "#"

In [8]:
# my own exception
type CannotPutAnimal <: Exception end

In [9]:
function putAnimal(a::Animal, x::Integer, y::Integer)
    if 0 < x < size(world,1) && 0 < y < size(world,2) && world[x,y] == "#"
        a.x = x
        a.y = y
        world[x,y] = a.name
        println("$(a.name) was put on the map")
    else
        throw(CannotPutAnimal())
    end
end

putAnimal (generic function with 1 method)

In [10]:
function removeAnimal(a::Animal)
    if a.x <= 0 || a.y <= 0
        return false
    else
        world[a.x,a.y] = "#"
        a.x = 0
        a.y = 0
        println("$(a.name) was removed from the map")
        return true
    end
end

removeAnimal (generic function with 1 method)

In [11]:
function distance(a::Animal, b::Animal) 
    sum = 0
    if a.x <= 0 || a.y <= 0 || b.x <= 0 || b.y <= 0
        return Inf
    else
        sum += abs(a.x - b.x)
        sum += abs(a.y - b.y)
        return sum
    end
end

distance (generic function with 1 method)

In [12]:
#creating animals
żaba = Victim("frog")
mysz = Victim("mouse")
lew = Predator("lion")
sęp = Predator("vulture")

Predator("vulture",0,0)

In [13]:
#putting animals in the world
putAnimal(żaba, 1, 3)
putAnimal(lew, 2, 4)
putAnimal(mysz, 4, 5)
putAnimal(sęp, 7, 8)

#lets see the world
world

frog was put on the map
lion was put on the map
mouse was put on the map
vulture was put on the map


10×10 Array{String,2}:
 "#"  "#"  "frog"  "#"     "#"      "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "lion"  "#"      "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"      "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "mouse"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"      "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"      "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"      "#"  "#"  "vulture"  "#"  "#"
 "#"  "#"  "#"     "#"     "#"      "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"      "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"      "#"  "#"  "#"        "#"  "#"

In [14]:
kot = Predator("cat")
putAnimal(kot, 2, 4)

LoadError: CannotPutAnimal()

In [15]:
#counting distance between animals
distance(żaba, mysz)

5

In [16]:
function interact(a::Predator, b::Victim)
    removeAnimal(b)
    return world
end

function interact(a::Victim, b::Predator)
    removeAnimal(a)
    putAnimal(a, rand(1:size(world,1)), rand(1:size(world,2)))
    return world
end

function interact(a::Predator, b::Predator)
    return "Wrrrr"
end

function interact(a::Victim, b::Victim)
    return "Beeee"
end


interact (generic function with 4 methods)

In [17]:
interact(sęp, mysz)

mouse was removed from the map


10×10 Array{String,2}:
 "#"  "#"  "frog"  "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "lion"  "#"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"  "#"  "#"  "vulture"  "#"  "#"
 "#"  "#"  "#"     "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"  "#"  "#"     "#"     "#"  "#"  "#"  "#"        "#"  "#"

In [18]:
interact(żaba, lew)

frog was removed from the map
frog was put on the map


10×10 Array{String,2}:
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "frog"  "#"  "#"  "lion"  "#"  "#"  "#"  "#"        "#"  "#"
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "vulture"  "#"  "#"
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "#"        "#"  "#"
 "#"     "#"  "#"  "#"     "#"  "#"  "#"  "#"        "#"  "#"

In [19]:
interact(żaba, mysz)

"Beeee"

In [20]:
interact(lew, sęp)

"Wrrrr"